APP_DATABASE_RETRY_ATTEMPTS: 3
APP_DATABASE_RETRY_BACKOFF: 500
APP_DEPLOY_URL: http://localhost:8080/api/v1/url-shortener
DATASOURCE_URL: jdbc:h2:file:~/data/database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
DRIVER_CLASS_NAME: org.h2.Driver
DB_USERNAME: sa
DB_PASSWORD: password
DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
DDL_AUTO: update

