-- Initial schema for the URL shortener.

CREATE TABLE url (
    url_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url VARCHAR(2048) NOT NULL,
    shorten_url  VARCHAR(10)   NOT NULL,
    created_by   VARCHAR(50)   NOT NULL,
    created_at   TIMESTAMP     NOT NULL,
    modified_by  VARCHAR(50)   NOT NULL,
    modified_at  TIMESTAMP,
    CONSTRAINT uk_url_shorten  UNIQUE (shorten_url),
    CONSTRAINT uk_url_original UNIQUE (original_url)
);
