-- Users table backing the in-app authentication (register + login).
-- Passwords are stored as BCrypt hashes (never in clear text).

CREATE TABLE users (
    user_id    INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50)  NOT NULL,
    password   VARCHAR(100) NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);
